export const COLOR = {
  ksPrimaryColorMain: '#2135EE',
  ksSecondaryColorMain: '#E6E9ED',
  ksTertiaryColorMain: '#DCDFEC',
  ksBodyColorMain: 'rgba(0, 0, 0, 0.6)',
  ksBorderColorMain: 'rgba(0, 0, 0, 0.1)',
  ksBackgroundColorMain: '#E9EBF1',
  ksBackgroundColor2: '#F0F2F5',
  ksBackgroundColor3: '#FFFFFF',
  ksBackgroundColor4: '#DFE1E5',
  ksProductColorBtn2: '#FF7817',
  ksProductColorBtn3: '#B4D5FF',
  ksProductColorBtn4: '#818181',
  ksSuccessColorDefault: '#0EC122',
  ksWarningColorDefault: '#FFC107',
  ksInfoColorDefault: '#0D6EFD',
  ksErrorColorDefault: '#EF5350',
  ksBlackColorDefault: '#000000',
  ksWhiteColorDefault: '#FFFFFF',
  ksGreyColorDefault: '#808080'
};
